### ISSUE TITLE
Binary please :>

### ISSUE THREAD

**Issue by buikhoa40** [apsun/AbsoluteTouchEx#1]
12Gb of VS download for building this program... 👎 
A prebuilt release would be great... 👍

**Comment by apsun** [comment]
As this project is still experimental, I would prefer not releasing binaries until it's been tested some more. Last I checked it had some weird issues with cursor jitter, which I need to fix. Don't worry, binaries are coming soon, probably within the next month or so.

**Comment by apsun** [comment]
Done. You can grab it at https://github.com/apsun/AbsoluteTouchEx/releases/tag/1.0.0

Expect lots of bugs. I've only tested it so far on my own touchpad. Feedback is highly appreciated, please create a new issue if you find any bugs.
