### ISSUE TITLE
cant make it work

### ISSUE THREAD

**Issue by alyssonpombo** [apsun/AbsoluteTouchEx#16]
i dont have the programing skills, i cant make it work... im i doing something wrong?

windows 10 pro, want to put it to work on onenote, to move as touch.

**Comment by apsun** [comment]
I don't think OneNote would use raw input (which AbsoluteTouchEx requires). Typically only games use raw input. So unfortunately to answer your question, AbsoluteTouchEx is incompatible with OneNote, sorry.
