### ISSUE TITLE
global absolute touch?

### ISSUE THREAD

**Issue by based0000** [apsun/AbsoluteTouchEx#17]
i'd like to use it like your original AbsoluteTouch
what do i have to hook?
maybe a list of commands?
idk im confused plz help qwq

**Comment by apsun** [comment]
Unfortunately AbsoluteTouchEx does not (well, really, cannot) work globally. It works by hooking the raw input API, which really only games use. Short of doing some magic in the kernel, you can't have your cake and eat it too, so you'll have to either use AbsoluteTouch to emulate cursor movement globally or AbsoluteTouchEx to inject raw input data.
