### ISSUE TITLE
Program detects where I touch touchpad, but doesn't move cursor

### ISSUE THREAD

**Issue by FeliKQ** [apsun/AbsoluteTouchEx#7]
I have notebook Lenovo Legion Y530.
I've downloaded every driver/program what I needed to install.
When I launch program, press Shift+F6, program detects all the touches on touchpad, but cursor isn't moving anywhere...
Ask any questions. I really want to have touchscreen. :O

**Comment by Opusno13** [comment]
> When I launch program, press Shift+F6, program detects all the touches on touchpad, but cursor isn't moving anywhere...

I mean, there are numbers in console, like 0,0 if I tap at left top corner.

**Comment by apsun** [comment]
AbsoluteTouchEx only works with programs using raw input (typically games). Are you trying to use it just on your normal desktop? It won't do anything there.

**Comment by FeliKQ** [comment]
It doesn't working anywhere.
osu!, desktop, any program.
I said about numbers just to know, what program knows where am I touching.
Also yes, I have raw input enabled in osu!

**Comment by apsun** [comment]
Did you run it through command prompt like the examples in the instructions? If you double clicked the exe it just launches the demo (which is what prints the coordinates).

**Comment by FeliKQ** [comment]
I made .bat with this: "atloader.exe %LocalAppData%\osu!\osu!.exe" in x64 folder (i'm 64 bit). If I run it with admin permissions, osu! isn't launching. If I double click it (.bat file) it launches osu! and no matter what cursor doesn't move (yes, I pressed Shift+F6).
heeeeeeeeeeeelp!..
:<

**Comment by apsun** [comment]
From the readme:

>for the bitness version that you intend to run, not for the bitness of your operating system

For osu! you should be using the x86 version, since the game is a 32-bit program.

**Comment by FeliKQ** [comment]
OK, I'm stupid. Now it works. 
Thank you very much for you work and help!

**Comment by Opusno13** [comment]
Also peppy allowed to play with AbsoluteTouch(Ex). There's Twitter post: https://web.archive.org/web/20191002211906/https://twitter.com/ppy/status/1179503767584067584.
So you can delete warning in ReadMe.

**Comment by apsun** [comment]
I'll keep it just because of the potential that someone will use it for something other than osu! (though I also personally only ever used it for that), but thanks for confirming!
